### ISSUE TITLE
[Documentation Update]: New DCC-EX Mega + WiFi 'Plug & Play' Starter Kit 4.1.1

### ISSUE THREAD

**Issue by Kcsmith0708** [DCC-EX/dcc-ex.github.io#425] opened 2022-10-24 23:25 UTC
### Documentation details

Create a New 'Related Projects' web page for **"DCC-EX Mega + WiFi 'Plug & Play' Starter Kit v4.1.1"**

A Complete  & running sample DCC-EX Mega + WiFi EXRAIL Command Station with Engine Driver & WiThrottle controllers to operate DCC loco on a Station A & B layout.

Includes;
 _CommandStation-EX_Courses_4.1.1         Complete CS pre-setup & ready to run
 DCC-EX Plug & Play Starter Kit.pdf          Installation & Operations guide
 Sample MP3 Files                                     DFPlayer mini Sound files._

I have this all prepackaged in a **DCC-EX Mega Plug&Play Starter Kit 4.1.1.zip**  file ready for testing and minor editing before giving it to the public.

The web pages can be built by cutting and pasting samples from the Two myEXRAIL_Courses 100 and 200 level in side the CommandStation-EX folder.

See sample .pdf file
[DCC-EX Mega+WiFi 'Plug & Play' with Engine Driver Throttle Controller.pdf](https://github.com/DCC-EX/dcc-ex.github.io/files/9855972/DCC-EX.Mega%2BWiFi.Plug.Play.with.Engine.Driver.Throttle.Controller.pdf)

**Comment by peteGSX** [comment] 2022-10-28 05:37
Duplicate of https://github.com/DCC-EX/dcc-ex.github.io/issues/423

**Closed as completed by peteGSX** 2022-10-28 05:37 UTC
Labels: Documentation
