### ISSUE TITLE
Check image issue with .JPG instructions on EX-RAIL Intro page

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#106] opened 2022-01-12 21:07 UTC
The pictures at the begining of EX-RAIL intro page on how to make a myAutomation.h are missing.

These are .JPG files, and are in the same folder as .PNG track diagrams that correctly display further down the page.

These images have previously worked fine.

**Comment by Condo-Colin** [comment] 2022-01-13 02:58
Looks like a change was done as part of the"fix broken links" PR, to change the image filenames from Title case to lower case, but the image names are either already lower case, or had been changed to match. So it should still work?

**Comment by cjmayo** [comment] 2022-01-13 20:08
OK. I believe that is fixed now, by #109 and #110 (looks like #108 was a misunderstanding by me, no harm done as it was in the gh-pages branch). I decided to get straight on and merge those myself, do let me know if that was a problem - and by all means revert #109 if that isn't wanted (I hope we don't need it again).

My analysis of the issue is that the old image filenames e.g. Setup1.jpg were still present on GitHub Pages and the deployment/publishing/storage is case-insensitive so never overwrote them with e.g. setup1.jpg.

By deleting the images with the old filenames I forced the new filenames to be published on the merge of #109 to the sphinx branch.

Please check it really is fixed.

**Comment by cjmayo** [comment] 2022-01-14 19:44
When the EX-RAIL page and images were first committed e6935594d9b5 they had the setup1.jpg filename and Setup1.jpg target in the image directive of the page.

Looks like the cause was that the GitHub action uses macOS which has a case-insensitive filesystem, and when Sphinx copied the images from /docs/_static/images/ to /_static/images/ it renamed them Setup1.jpg.

Suggest changing the Action to Ubuntu to make this impossible #111.

**Comment by Condo-Colin** [comment] 2022-01-16 01:31
Thanks Chris! You know all about it mate, so I'll leave it to you and Fred, but that sounds reasonable.
The images are certainly back up online and working. 😎👍

**Comment by cjmayo** [comment] 2022-01-25 19:59
Thanks for finding and checking. The build workflow is not running on Ubuntu, hopefully that makes it impossible to create a similar problem in future.

**Closed as completed by cjmayo** 2022-01-25 19:59 UTC
